# Generated by Django 6.0.6 on 2026-06-30 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='例如 MTG-DEU-FRA15-VXLAN-6863-01', max_length=255, unique=True, verbose_name='设备名称')),
                ('vendor', models.CharField(blank=True, default='Huawei', max_length=128, verbose_name='厂商')),
                ('os_version', models.CharField(blank=True, help_text='例如 V200R024C00SPC500', max_length=255, verbose_name='软件版本')),
                ('chassis_type', models.CharField(blank=True, help_text='例如 CE6863-48S6CQ', max_length=255, verbose_name='设备型号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如 100GE1/0/1, Eth-Trunk0, Loop100', max_length=128, verbose_name='接口名称')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='端口描述')),
                ('phy_status', models.CharField(blank=True, help_text='up / down', max_length=32, verbose_name='物理层状态')),
                ('protocol_status', models.CharField(blank=True, help_text='up / down', max_length=32, verbose_name='协议层状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='asset_management.device', verbose_name='归属设备')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'ordering': ['device', 'name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LLDPNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_device', models.CharField(blank=True, max_length=255, verbose_name='对端设备名')),
                ('remote_interface', models.CharField(blank=True, max_length=128, verbose_name='对端接口名')),
                ('local_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lldp_neighbor', to='asset_management.interface', verbose_name='本端接口')),
            ],
            options={
                'verbose_name': 'LLDP邻居',
                'verbose_name_plural': 'LLDP邻居',
            },
        ),
        migrations.CreateModel(
            name='Transceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(blank=True, help_text='例如 100GBASE_Active_Optical_Cable', max_length=255, verbose_name='模块类型')),
                ('vendor_name', models.CharField(blank=True, max_length=128, verbose_name='模块厂商')),
                ('part_number', models.CharField(blank=True, max_length=128, verbose_name='部件编号')),
                ('serial_number', models.CharField(blank=True, max_length=128, verbose_name='序列号')),
                ('transfer_distance', models.CharField(blank=True, help_text='例如 16(Optical Cable)', max_length=128, verbose_name='传输距离')),
                ('connector_type', models.CharField(blank=True, help_text='例如 LC, -', max_length=64, verbose_name='连接器类型')),
                ('wavelength', models.CharField(blank=True, max_length=64, verbose_name='波长(nm)')),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transceiver', to='asset_management.interface', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': '光模块',
                'verbose_name_plural': '光模块',
            },
        ),
    ]
