# Generated by Django 6.0.6 on 2026-06-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('physical', '物理接口'), ('logical', '逻辑接口')], default='physical', help_text='physical=物理数据端口 logical=Eth-Trunk/Loop/NULL等', max_length=16, verbose_name='接口类型'),
        ),
        migrations.AddField(
            model_name='transceiver',
            name='manufacturing_date',
            field=models.CharField(blank=True, help_text='例如 2019-5-26', max_length=64, verbose_name='生产日期'),
        ),
    ]
